apiVersion: v1
kind: Secret
metadata:
  name: camframe-analyzer
  namespace: crowd-analytics
data:
  AzureWebJobsStorage: #{funcStorage}#
  FUNCTIONS_WORKER_RUNTIME: #{funcRuntime}#
  APPINSIGHTS_INSTRUMENTATIONKEY: #{appInsightsKey}#
  serviceBusConnection: #{serviceBusConnection}#
  KEDA_SERVICE_BUS_CONNECTION: #{kedaServiceBusConnection}#
  camFrameStorageConnection: #{camFrameStorageConnection}#
  cognitiveKey: #{cognitiveKey}#
  cognitiveEndpoint: #{cognitiveEndpoint}#
  cosmosDbEndpoint: #{cosmosDbEndpoint}#
  cosmosDbKey: #{cosmosDbKey}#
  faceWorkspaceDataFilter: #{faceWorkspaceDataFilter}#