apiVersion: v1
kind: Secret
metadata:
  name: crowd-analyzer
  namespace: crowd-analytics
data:
  AzureWebJobsStorage: #{funcStorage}#
  FUNCTIONS_WORKER_RUNTIME: ZG90bmV0 # dotnet
  APPINSIGHTS_INSTRUMENTATIONKEY: #{appInsightsKey}#
  serviceBusConnection: #{serviceBusConnection}#
  KEDA_SERVICE_BUS_CONNECTION: #{kedaServiceBusConnection}#
  origin: Q3Jvd2REZW1vZ3JhcGhpY3MuVjEuMC4w # CrowdDemographics.V1.0.0
  checkForDbConsistency: dHJ1ZQ== #true
  cosmosDbEndpoint: #{cosmosDbEndpoint}#
  cosmosDbKey: #{cosmosDbKey}#
  faceWorkspaceDataFilter: Q29udG9zby5Dcm93ZEFuYWx5dGljcw== # Contoso.CrowdAnalytics
  demographicsWindowMins: NjA= # 60