apiVersion: v1
kind: Secret
metadata:
  name: cognitive-orchestrator
  namespace: crowd-analytics
data:
  AzureWebJobsStorage: #{funcStorage}#
  FUNCTIONS_WORKER_RUNTIME: #{funcRuntime}#
  APPINSIGHTS_INSTRUMENTATIONKEY: #{appInsightsKey}#
  serviceBusConnection: #{serviceBusConnection}#
  KEDA_SERVICE_BUS_CONNECTION: #{kedaServiceBusConnection}#